# Generated by Django 5.2.10 on 2026-02-02 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('superset_dashboard_id', models.IntegerField(blank=True, null=True)),
                ('dashboard_uuid', models.UUIDField(unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('allowed_roles', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Embedded Dashboard',
                'verbose_name_plural': 'Embedded Dashboards',
                'db_table': 'superset_embedded_dashboards',
            },
        ),
        migrations.CreateModel(
            name='GuestToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superset.embeddeddashboard')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest Token',
                'verbose_name_plural': 'Guest Tokens',
                'db_table': 'superset_guest_tokens',
            },
        ),
    ]
